# Docker Compose file for Globetrotter AI web app with n8n orchestration
version: '3.8'
services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - 5678:5678
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      # - N8N_BASIC_AUTH_USER=admin
      # - N8N_BASIC_AUTH_PASSWORD=admin
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - WEBHOOK_TUNNEL_URL=http://localhost:5678
      - N8N_CORS_ALLOW_ORIGIN=*
      - N8N_CORS_ALLOW_METHODS=GET,POST,OPTIONS
    volumes:
      - n8n_data:/home/node/.n8n
  web:
    build: ./web
    ports:
      - 3001:3000
    depends_on:
      - n8n
volumes:
  n8n_data:
